// <auto-generated />
namespace DER.WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LogUsuario_DadosMestres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogUsuario_DadosMestres));
        
        string IMigrationMetadata.Id
        {
            get { return "202012031917556_LogUsuario_DadosMestres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
