namespace DER.WebApp.Domain.Models.Enum
{
    public enum TabelaDadosMestresEnum
    {
        Concessionaria = 1,
        DivisaoRegional = 2,
        IGPM = 3,
        Municipio = 4,
        NaturezaJuridica = 5,
        PI = 6,
        Rodovia = 7,
        TipoInteressado = 8,
        TipoOcupacao = 9,
        UA = 10,
        UFESP = 11,
        Unidade = 12,
        TipoEmpresa = 13,
        TipoDeConcessao = 14,
        TipoDeDocumento = 15,
        OrigemDaSolicitacao = 16,
        SituacaoDaSolicitacao = 17,
        Area = 18,
        ResidenciaConservacao = 19,        
        TipoDePassagem = 20,
        TipoDeImplantacao = 21,
        TipoDeInterferencia = 22,
        Lado = 23,
        TipoDeDocumentoOcupacao = 24,
        TipodeDocumentoInteressado = 25,
        OcorrenciaAssunto = 26,
        OcorrenciaSeveridade = 27,
        OcorrenciaStatus = 28,
        OcorrenciaTrecho = 29,
        Dispositivo = 30,
        AreasGramadasLevantamento = 33,
        DrenagensLinearesLevantamento = 34,
        CercasLevantamento = 35,
        FaixasRolamentoLevantamento = 36,
        PassivosAmbientaisLinLevantamento = 37,
        OaeLevantamento = 38,
        PavimentacoesLevantamento = 39,
        PavimentosRigidosLevantamento = 40,
        SegurancaBordoLevantamento = 41,
        RocadasLevantamento = 42,
        SegurancaCanteiroLevantamento = 43,
        SegurancaGuardaCorpoLevantamento = 44,
        SinalFaixaBordoLevantamento = 45,
        SinalFaixaCentralLevantamento = 46,
        TerceiraFaixaLevantamento = 47,
        TachaFaixaBordoLevantamento = 48,
        TachaFaixaCentralLevantamento = 49,
        TiposPistaLevantamento = 50,
        TuneisLevantamento = 51,
        AcostamentosLevantamento = 52,
        SituacaoDaOcupacao = 117
    }
}